name: libre_doc_converter
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/josereia/libre_doc_converter

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  very_good_analysis: ^5.0.0+1
dependencies:
  path: ^1.8.3
